version: "3.8"
services:

  kong-database:
    image: postgres:15.4-alpine3.18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./docker-compose-volume:/var/lib/postgresql/data
    
  kong-migrations-bootstrap:
    build:
      context: .
      args:
        - KONG_VERSION=${KONG_VERSION}
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_LOG_LEVEL=${KONG_LOG_LEVEL:-info}
      - KONG_PLUGINS=bundled,easter_egg
      - KONG_LUA_PACKAGE_PATH=/usr/local/bin/easter_egg/?.lua;;
    command: kong migrations bootstrap
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kong-database

  kong-migrations-up:
    build:
      context: .
      args:
        - KONG_VERSION=${KONG_VERSION}
        - RUN_MIGRATIONS=${RUN_MIGRATIONS}
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_LOG_LEVEL=${KONG_LOG_LEVEL:-info}
      - KONG_PLUGINS=bundled,easter_egg
      - KONG_LUA_PACKAGE_PATH=/usr/local/bin/easter_egg/?.lua;;
    command: sh -c "sleep 10 && kong migrations up && kong migrations finish"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kong-migrations-bootstrap

  kong:
    build:
      context: .
      args:
        - KONG_VERSION=${KONG_VERSION}
    ports:
      - 8000:8000 # Proxy
      - 8443:8443
      - 8001:8001 # AdminAPI
      - 8444:8444
      - 8002:8002 # Kong Manager (GUI)
      - 8445:8445
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001 reuseport backlog=16384, 0.0.0.0:8444 http2 ssl reuseport backlog=16384
      - KONG_SSL_PROTOCOLS="TLSv1.2 TLSv1.3"
      - KONG_SSL_CERT=/opt/certs/kong.crt
      - KONG_SSL_CERT_KEY=/opt/certs/kong.key
      - KONG_ADMIN_GUI_SSL_CERT=/opt/certs/kong.crt
      - KONG_ADMIN_GUI_SSL_CERT_KEY=/opt/certs/kong.key
      - KONG_ADMIN_GUI_URL=https://localhost:8445
      - KONG_ADMIN_GUI_API_URL=https://localhost:8444
      - KONG_LOG_LEVEL=${KONG_LOG_LEVEL:-info}
      - KONG_PLUGINS=bundled,easter_egg
      - KONG_LUA_PACKAGE_PATH=/usr/local/bin/easter_egg/?.lua;;
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kong-migrations-up
