version: "3.8"
services:

  kong-database:
    image: postgres:15.4-alpine3.18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./docker-compose-volume:/var/lib/postgresql/data
    
  kong-migrations-bootstrap:
    build:
      context: .
      args:
        - VERSION=${VERSION}
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
    command: kong migrations bootstrap
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kong-database

  kong-migrations-up:
    build:
      context: .
      args:
        - VERSION=${VERSION}
        - RUN_MIGRATIONS=${RUN_MIGRATIONS}
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
    command: kong migrations up && kong migrations finish
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kong-migrations-bootstrap

  kong:
    build:
      context: .
      args:
        - VERSION=${VERSION}
    ports:
      - 8000:8000 # Proxy
      - 8443:8443
      - 8001:8001 # AdminAPI
      - 8444:8444
      - 8002:8002 # Kong Manager (GUI)
      - 8445:8445
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      # - KONG_ADMIN_GUI_API_URL=http://localhost:8000/admin-api # Loop-back AdminAPI for Kong Manager to use on a same host and port
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kong-migrations-up
